use bitfield::bitfield;

bitfield! {
    pub struct ICSR(u32);
    impl Debug;

    // interrupt pending generated by NVIC
    pub isr_pending, _: 22;
    // wether interrupt serviced after debug halt or not
    pub isr_preemt, _: 23;
    pub st_pending, set_st_pending: 26;
    // if no interrupt pending -> 0 else interrupt number
    pub vect_pending, _: 20, 12;
}

impl ICSR {
    pub const ADDRESS: u32 = 0xE000E004;
}
